#!/usr/bin/env python3
"""Convert Trinkets.xlsx into trinkets.js for the web app (stdlib only).

Usage: python3 scripts/convert.py [path/to/Trinkets.xlsx]
"""
import json
import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"
ROOT = Path(__file__).resolve().parent.parent


def read_sheets(path):
    with zipfile.ZipFile(path) as z:
        strings = [
            "".join(t.text or "" for t in si.iter(f"{NS}t"))
            for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall(f"{NS}si")
        ]
        sheets = []
        for n in (1, 2):
            rows = []
            root = ET.fromstring(z.read(f"xl/worksheets/sheet{n}.xml"))
            for r in root.iter(f"{NS}row"):
                row = {}
                for c in r.findall(f"{NS}c"):
                    col = re.match(r"[A-Z]+", c.get("r")).group()
                    v = c.find(f"{NS}v")
                    inline = c.find(f".//{NS}t")
                    if c.get("t") == "s" and v is not None:
                        row[col] = strings[int(v.text)]
                    elif inline is not None:
                        row[col] = inline.text
                    elif v is not None:
                        row[col] = v.text
                row = {k: v.strip() for k, v in row.items() if v and v.strip()}
                if row:
                    rows.append(row)
            sheets.append(rows)
        return sheets


def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1 else Path.home() / "Downloads/Trinkets.xlsx")
    trinket_rows, location_rows = read_sheets(src)

    trinkets = [r["B"] for r in trinket_rows[1:] if "B" in r]

    header = location_rows[0]
    cols = [c for c in sorted(header) if c != "A"]
    locations = {header[c]: [r[c] for r in location_rows[1:] if c in r] for c in cols}

    out = ROOT / "trinkets.js"
    data = {"trinkets": trinkets, "locations": locations}
    out.write_text("// Generated by scripts/convert.py — do not edit by hand.\n"
                   f"window.TRINKET_DATA = {json.dumps(data, ensure_ascii=False, indent=1)};\n")
    print(f"Wrote {out.name}: {len(trinkets)} trinkets, "
          + ", ".join(f"{k} ({len(v)})" for k, v in locations.items()))


if __name__ == "__main__":
    main()
